# -*- coding: utf-8 -*-
"""Python_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G34OWlFgN14XCKcwiEKJFjJ4i7MXSVTf
"""

!pip install streamlit
!npm install localtunel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# st.title('Hello Streamlit')

!npm install localtunnel

!streamlit run /content/app.py & npx localtunnel --port 8501 &  curl ipv4.icanhazip.com

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# ######## Import the required pacakges ############
# import streamlit as st
# import google.generativeai as genai
# from PIL import Image
# 
# ####### Provide your api key ###################
# api_key="AIzaSyAq_0rFskzP-1dHnPHx01yW2RemkJQdx9Q"
# genai.configure(api_key=api_key)
# 
# ######## Choose the heading ###############
# st.header("Image analytics")
# 
# ########## Upload a file ##################
# uploaded_file=st.file_uploader("Upload an image",type=["png","jpg","jpeg"])
# 
# if uploaded_file is not None:
#     st.image(Image.open(uploaded_file))
# 
# ############ What you want ask ####################
# prompt=st.text_input("Enter the text")
# 
# ######### Use genai skill ##########################
# 
# if st.button("GET RESPONSE"):
#     img=Image.open(uploaded_file)
#     model=genai.GenerativeModel("gemini-1.5-flash")
#     response=model.generate_content([prompt,img])
#     st.markdown(response.text)

!streamlit run /content/app.py & npx localtunnel --port 8501 &  curl ipv4.icanhazip.com